spring:
  datasource:
    url: jdbc:postgresql://ec2-23-21-171-249.compute-1.amazonaws.com:5432/d7v2pg294e42r2?sslmode=require #${JDBC_DATABASE_URL}
    username: joecgylmcbgnon #${JDBC_DATABASE_USERNAME}
    password: c75503bd5c557176aa07e368358951d134347d1b55fd8648d799ee6475d63fe1 #${JDBC_DATABASE_PASSWORD}
    
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect